title: "nutt's blog"
description: "Writing things down."
author: "nutt"
url: "https://nutt.cc/"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - jekyll-paginate
